/**
 * The shape of all learning content. Lessons are plain data files that follow
 * these types; TypeScript refuses to build if a lesson is missing a part.
 * See docs/CONTENT_FORMAT.md for a friendly walkthrough.
 */
import type { Language } from "../runners/types";

export type Json = string | number | boolean | null | Json[] | { [key: string]: Json };

interface TestBase {
  /** Shown in the results list. A sensible default is generated when missing. */
  label?: string;
  /** Extra advice shown when this test fails, e.g. "Check if you multiplied by nights". */
  hint?: string;
  /** Input lines for this test (overrides the exercise's `stdin`). */
  stdin?: string[];
}

/** Python exercise tests. */
export type PyTest =
  /** The whole printed output (including prompts and typed input) must match. */
  | (TestBase & { kind: "output"; expect: string })
  /** The output must contain each of these pieces of text. */
  | (TestBase & { kind: "contains"; expect: string | string[] })
  /** After running the code, evaluate `call` and compare with `expect`. */
  | (TestBase & { kind: "call"; call: string; expect: Json })
  /** After running the code, variable `variable` must equal `expect`. */
  | (TestBase & { kind: "var"; variable: string; expect: Json })
  /** The program (or `call`, when given) must raise this exception type. */
  | (TestBase & { kind: "raises"; call?: string; expect: string })
  /** Custom Python check. Has `ns` (your variables), `output`, `lines` and `fail(msg)`. */
  | (TestBase & { kind: "py"; label: string; check: string })
  /**
   * The source code must (or must not, with `negate`) match a regular expression.
   * Comments are removed first, unless `raw` is true.
   */
  | { kind: "source"; label: string; pattern: string; flags?: string; negate?: boolean; raw?: boolean; message: string };

/** SQL exercise tests (used from Phase 3). */
export interface SqlCheck {
  /** The solution's result is the expected answer. */
  expectedQuery?: string;
  /** For INSERT/UPDATE/DELETE: run this afterwards on both databases and compare. */
  checkQuery?: string;
  orderMatters?: boolean;
}

export interface Exercise {
  id: string;
  title: string;
  /** Markdown. What to build. */
  prompt: string;
  starter: string;
  stdin?: string[];
  files?: Record<string, string>;
  tests: PyTest[];
  sql?: SqlCheck;
  /** Three hints: a nudge → a stronger hint → almost the solution. */
  hints: [string, string, string];
  solution: { code: string; explanation: string };
  /** At least one plausible wrong answer. The content checker makes sure each one FAILS. */
  wrongAnswers: string[];
}

export type QuizItem = {
  id: string;
  /** predict = what does this print? · bug = find the mistake · choice = multiple choice */
  kind: "predict" | "bug" | "choice";
  question: string;
  code?: string;
  stdin?: string[];
  options: string[];
  /** Index into options. For "predict", the checker runs `code` and confirms this option. */
  answer: number;
  explanation: string;
};

export interface WorkedExample {
  /** Markdown shown above the code. */
  intro?: string;
  code: string;
  stdin?: string[];
  files?: Record<string, string>;
  /** Set when the example is *meant* to crash (e.g. the "reading errors" lesson). */
  expectError?: string;
}

export interface LessonData {
  goal: string;
  example?: WorkedExample;
  tryIt?: { prompt: string; code?: string; stdin?: string[] };
  exercises: Exercise[];
  quiz: QuizItem[];
}

/** Everything generated by `npm run content` for one lesson (committed to git). */
export interface GeneratedLesson {
  example?: {
    output: string;
    error: import("../runners/types").RunError | null;
    trace: import("../runners/python/types").TraceStep[];
    truncated: boolean;
  };
}

// ---- Track outline ---------------------------------------------------------

export interface LessonRef {
  id: string;
  title: string;
  kind?: "lesson" | "project" | "capstone";
}

export interface ModuleOutline {
  id: string;
  title: string;
  summary: string;
  lessons: LessonRef[];
  /** Java only: how this compares to what you know from Python. */
  comparedToPython?: string;
}

export interface TrackOutline {
  id: Language;
  title: string;
  tagline: string;
  status: "ready" | "coming-soon";
  modules: ModuleOutline[];
}

/** Helper so lesson files get type-checking and autocompletion. */
export function defineLesson(data: LessonData): LessonData {
  return data;
}
