/**
 * Content generator + checker.
 *
 *   npm run content   → verify every lesson AND (re)write each generated.json
 *   npm run verify    → verify only; fails if a generated.json is out of date
 *
 * Options:  --only=<text>   only lessons whose path contains <text>
 *           --verbose       also print the feedback each wrong answer receives
 *
 * For every lesson it checks that:
 *   - the lesson has all its parts (goal, sections, 3 hints, …)
 *   - the worked example runs (and its trace is generated by the real interpreter)
 *   - every exercise's solution PASSES all tests
 *   - every listed wrong answer FAILS at least one test
 *   - every "predict the output" question's answer is the real output
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { isDeepStrictEqual } from "node:util";
import { pythonTrack } from "../content/python/track.ts";
import type { GeneratedLesson, LessonData, TrackOutline } from "../src/content/types.ts";
import { REQUIRED_SECTIONS, splitSections } from "../src/content/markdownSections.ts";
import { runSourceTests } from "../src/checking/sourceTests.ts";
import { createNodePython } from "./lib/node-python.ts";

const root = resolve(import.meta.dirname, "..");
const args = process.argv.slice(2);
const checkOnly = args.includes("--check");
const verbose = args.includes("--verbose");
const only = args.find((a) => a.startsWith("--only="))?.slice(7);

const tracks: TrackOutline[] = [pythonTrack];
const core = await createNodePython();

let failures = 0;
let warnings = 0;
let lessonsChecked = 0;
let exercisesChecked = 0;
const pending: string[] = [];

const normalize = (text: string) =>
  text
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((l) => l.trimEnd())
    .join("\n")
    .replace(/\n+$/, "");

function fail(path: string, message: string) {
  failures++;
  console.log(`  ✗ ${path}: ${message}`);
}
function warn(path: string, message: string) {
  warnings++;
  console.log(`  ! ${path}: ${message}`);
}

function runTests(code: string, ex: LessonData["exercises"][number]) {
  const py = core.check({ code, tests: ex.tests, stdin: ex.stdin, files: ex.files });
  return [...py, ...runSourceTests(code, ex.tests)];
}

for (const track of tracks) {
  console.log(`\n${track.title}`);
  for (const module of track.modules) {
    // Folders on disk that aren't in the outline are probably typos.
    const moduleDir = resolve(root, "content", track.id, module.id);
    if (existsSync(moduleDir)) {
      for (const dir of readdirSync(moduleDir)) {
        if (!module.lessons.some((l) => l.id === dir)) fail(`${track.id}/${module.id}/${dir}`, "folder is not listed in track.ts");
      }
    }

    for (const ref of module.lessons) {
      const path = `${track.id}/${module.id}/${ref.id}`;
      if (only && !path.includes(only)) continue;
      const dir = resolve(moduleDir, ref.id);
      if (!existsSync(resolve(dir, "lesson.ts"))) {
        pending.push(path);
        continue;
      }
      lessonsChecked++;
      const before = failures;
      const data: LessonData = (await import(pathToFileURL(resolve(dir, "lesson.ts")).href)).default;
      const kind = ref.kind ?? "lesson";

      // --- structure ------------------------------------------------------
      const mdPath = resolve(dir, "lesson.md");
      const sections = existsSync(mdPath) ? splitSections(readFileSync(mdPath, "utf8")) : {};
      for (const s of REQUIRED_SECTIONS[kind]) if (!sections[s]) fail(path, `lesson.md is missing "## ${s}"`);
      if (sections.concept) {
        const words = sections.concept.replace(/```[\s\S]*?```/g, "").split(/\s+/).filter(Boolean).length;
        if (words > 170) warn(path, `concept is ${words} words (aim for ≤150)`);
      }
      if (!data.goal) fail(path, "missing goal");
      if (kind === "lesson" && !data.example) fail(path, "a lesson needs a worked example");
      if (kind === "lesson" && (data.quiz.length < 2 || data.quiz.length > 3)) warn(path, `has ${data.quiz.length} quiz questions (aim for 2–3)`);
      if (data.exercises.length === 0) fail(path, "no exercises");
      const ids = new Set<string>();
      for (const ex of data.exercises) {
        if (ids.has(ex.id)) fail(path, `duplicate exercise id ${ex.id}`);
        ids.add(ex.id);
      }
      const qids = new Set<string>();
      for (const q of data.quiz) {
        if (qids.has(q.id)) fail(path, `duplicate quiz id ${q.id}`);
        qids.add(q.id);
        if (q.answer < 0 || q.answer >= q.options.length) fail(path, `quiz ${q.id}: answer index out of range`);
      }

      // --- worked example → generated trace ------------------------------
      const generated: GeneratedLesson = {};
      if (data.example) {
        const t = core.trace({ code: data.example.code, stdin: data.example.stdin, files: data.example.files });
        const expected = data.example.expectError;
        if (expected && t.error?.type !== expected) fail(path, `example should raise ${expected} but got ${t.error?.type ?? "no error"}`);
        if (!expected && t.error) fail(path, `example crashed: ${t.error.type}: ${t.error.message}`);
        if (t.truncated) warn(path, "example trace was truncated; consider a shorter example");
        generated.example = { output: t.output, error: t.error, trace: t.steps, truncated: t.truncated };
      }

      // --- Try it code runs ------------------------------------------------
      if (data.tryIt?.code) {
        const r = core.run({ code: data.tryIt.code, stdin: data.tryIt.stdin ?? data.example?.stdin });
        if (r.error && !data.example?.expectError) fail(path, `tryIt code crashed: ${r.error.type}: ${r.error.message}`);
      }

      // --- exercises: solution passes, wrong answers fail ----------------
      for (const ex of data.exercises) {
        exercisesChecked++;
        if (ex.hints.length !== 3) fail(path, `${ex.id}: needs exactly 3 hints`);
        if (!ex.wrongAnswers.length) fail(path, `${ex.id}: needs at least one wrong answer`);
        if (!ex.tests.length) fail(path, `${ex.id}: has no tests`);

        const sol = runTests(ex.solution.code, ex);
        for (const r of sol.filter((r) => !r.passed)) fail(path, `${ex.id}: SOLUTION fails "${r.label}": ${r.message}`);

        ex.wrongAnswers.forEach((wrong, i) => {
          const res = runTests(wrong, ex);
          const failed = res.filter((r) => !r.passed);
          if (!failed.length) fail(path, `${ex.id}: wrong answer #${i + 1} PASSES all tests (tests are too weak)`);
          else if (verbose) console.log(`    · ${ex.id} wrong #${i + 1} → ${failed[0].label}: ${failed[0].message}`);
        });

        const starter = runTests(ex.starter, ex);
        if (starter.every((r) => r.passed)) warn(path, `${ex.id}: the starter code already passes`);
      }

      // --- predict-the-output questions -----------------------------------
      for (const q of data.quiz.filter((q) => q.kind === "predict")) {
        if (!q.code) {
          fail(path, `quiz ${q.id}: predict question needs code`);
          continue;
        }
        const r = core.run({ code: q.code, stdin: q.stdin });
        const actual = normalize(r.error ? `${r.stdout}${r.error.type}` : r.stdout);
        if (actual !== normalize(q.options[q.answer])) {
          fail(path, `quiz ${q.id}: the marked answer is ${JSON.stringify(q.options[q.answer])} but the code prints ${JSON.stringify(actual)}`);
        }
        const dupes = q.options.filter((o) => normalize(o) === actual);
        if (dupes.length > 1) fail(path, `quiz ${q.id}: more than one option equals the real output`);
      }

      // --- write or compare generated.json ---------------------------------
      const genPath = resolve(dir, "generated.json");
      const json = JSON.stringify(generated, null, 1) + "\n";
      if (checkOnly) {
        const existing = existsSync(genPath) ? JSON.parse(readFileSync(genPath, "utf8")) : null;
        if (!isDeepStrictEqual(existing, JSON.parse(json))) fail(path, "generated.json is out of date: run `npm run content`");
      } else if (Object.keys(generated).length) {
        writeFileSync(genPath, json);
      }

      if (failures === before) console.log(`  ✓ ${path} (${data.exercises.length} exercises, ${data.quiz.length} questions)`);
    }
  }
}

console.log(
  `\n${lessonsChecked} lessons, ${exercisesChecked} exercises checked · ${failures} failure(s) · ${warnings} warning(s)` +
    (pending.length ? ` · ${pending.length} lessons not written yet` : ""),
);
process.exit(failures ? 1 : 0);
